fix caddy

diff --git a/tiddly/rootfs/etc/services.d/caddy/run b/tiddly/rootfs/etc/services.d/caddy/run
--- a/tiddly/rootfs/etc/services.d/caddy/run
+++ b/tiddly/rootfs/etc/services.d/caddy/run
@@ -3,7 +3,12 @@ export CERTFILE=$(bashio::config 'certfile')
 export KEYFILE=$(bashio::config 'keyfile')
 
 envsubst < /etc/caddy/Caddyfile.template > /etc/caddy/Caddyfile
-echo "Caddyfile generated:"
+
 cat /etc/caddy/Caddyfile
+
+if [ ! -s /etc/caddy/Caddyfile ]; then
+  echo "❌ Error: /etc/caddy/Caddyfile is empty or invalid!"
+  exit 1
+fi
 
 exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
